# Generated by Django 5.2.5 on 2025-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no-show', 'No-Show'), ('late-cancel', 'Late Cancel')], default='active', max_length=20),
        ),
    ]
