# Generated by Django 5.2.5 on 2025-12-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bookingaddon'),
        ('payments', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Deposit amount received', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text="Fidden's commission (from service price)", max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount transferred to shop', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate applied (%)', max_digits=5)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payments.payment')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='api.shop')),
            ],
            options={
                'verbose_name': 'Shop Payout',
                'verbose_name_plural': 'Shop Payouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
