# Generated by Django 5.2.5 on 2025-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_shop_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deposit_status',
            field=models.CharField(choices=[('held', 'Held'), ('credited', 'Credited'), ('forfeited', 'Forfeited')], default='held', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='final_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final checkout amount (remaining + tip)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='final_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent for final checkout', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Full service price for commission calculation', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='tip_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base amount for tip calculation (usually service_price)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tip_option_selected',
            field=models.CharField(blank=True, choices=[('10', '10%'), ('15', '15%'), ('20', '20%'), ('custom', 'Custom')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tip_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
