# Generated by Django 5.2.5 on 2025-12-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_shop_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_capture_id',
            field=models.CharField(blank=True, help_text='PayPal capture ID for refunds', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='paypal_refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
