# Generated by Django 5.2.5 on 2025-09-23 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_service_discount_price_and_more'),
        ('payments', '0005_transactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Coupon applied to this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_coupon', to='api.coupon'),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount after applying coupon discount (if any)', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', 'coupon'], name='payments_co_user_id_10a3c6_idx')],
            },
        ),
    ]
