# Generated by Django 5.2.5 on 2025-12-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_fidden_pay_fields'),
        ('payments', '0005_paypal_refund_support'),
    ]

    operations = [
    ]
