# Generated by Django 5.2.5 on 2025-12-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_merge_20251210_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_payment_method',
            field=models.CharField(blank=True, choices=[('app', 'Pay via App'), ('cash', 'Pay in Cash')], help_text='How final payment is made: app or cash', max_length=10, null=True),
        ),
    ]
