# Generated by Django 5.2.5 on 2025-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_coupon_payment_coupon_amount_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
