# Generated by Django 5.2.5 on 2025-12-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_checkout_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prep_notes',
            field=models.TextField(blank=True, help_text='Stylist prep notes for appointment'),
        ),
    ]
