# Generated by Django 5.2.5 on 2026-01-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_booking_processing_end_booking_processing_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='forms_completed',
            field=models.BooleanField(default=False, help_text='Have all required forms been completed?'),
        ),
        migrations.AddField(
            model_name='booking',
            name='forms_required',
            field=models.BooleanField(default=False, help_text='Are intake forms required for this booking?'),
        ),
    ]
