# Generated by Django 5.2.5 on 2026-01-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_booking_forms_completed_booking_forms_required'),
        ('payments', '0009_walk_in_queue_support'),
    ]

    operations = [
    ]
