# Generated by Django 5.2.5 on 2025-10-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_merge_20251006_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
