# Generated by Django 5.2.5 on 2025-10-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_normalize_deposit_paid'),
    ]

    operations = [
    ]
