# Generated by Django 5.2.5 on 2025-10-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_merge_20251006_2210'),
        ('payments', '0018_match_db_total_amount'),
    ]

    operations = [
    ]
