version: '3.9'

services:
  web:
    build: .
    container_name: fidden_web
    command: ["gunicorn", "fidden.wsgi:application", "--bind", "0.0.0.0:8090"]
    volumes:
      - ./:/app
      - media:/app/media
      - staticfiles:/app/staticfiles
    ports:
      - "8090:8090"
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build: .
    container_name: fidden_celery
    command: celery -A fidden worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    container_name: fidden_celery_beat
    command: celery -A fidden beat --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:8
    container_name: fidden_redis
    ports:
      - "6385:6385"

volumes:
  media:
  staticfiles:
