# Generated by Django 5.2.5 on 2025-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of people who can take this service at a time'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the service in minutes', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
    ]
