# Generated by Django 5.2.5 on 2025-10-08 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='payments.booking'),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='rating_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.ratingreview'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.service'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='services',
            field=models.ManyToManyField(related_name='service_coupons', to='api.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicedisabledtime',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_times', to='api.service'),
        ),
        migrations.AddField(
            model_name='servicewishlist',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='api.service'),
        ),
        migrations.AddField(
            model_name='servicewishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.shop'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='api.shop'),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.shop'),
        ),
        migrations.AddField(
            model_name='favoriteshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.shop'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_coupons', to='api.shop'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='api.shop'),
        ),
        migrations.AddField(
            model_name='slot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.service'),
        ),
        migrations.AddField(
            model_name='slot',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.shop'),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='api.service'),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='api.shop'),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.slot'),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationfile',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_files', to='api.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='servicedisabledtime',
            unique_together={('service', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='servicewishlist',
            unique_together={('user', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteshop',
            unique_together={('user', 'shop')},
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['shop', 'start_time'], name='api_slot_shop_id_35700b_idx'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('service', 'start_time'), name='uniq_service_slot_start'),
        ),
        migrations.AddIndex(
            model_name='slotbooking',
            index=models.Index(fields=['shop', 'start_time', 'end_time'], name='api_slotboo_shop_id_1d5610_idx'),
        ),
        migrations.AddIndex(
            model_name='slotbooking',
            index=models.Index(fields=['service', 'start_time'], name='api_slotboo_service_f4cbba_idx'),
        ),
        migrations.AddConstraint(
            model_name='slotbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('user', 'slot'), name='uniq_user_slot_confirmed'),
        ),
    ]
