# Generated by Django 5.2.5 on 2025-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_capacity_service_duration_shop_shop_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='close_days',
            field=models.JSONField(default=list, help_text="List of closed days (e.g., ['monday', 'tuesday'])"),
        ),
    ]
