# Generated by Django 5.2.5 on 2025-10-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='deposit_amount',
        ),
    ]
