# Generated by Django 5.2.5 on 2025-10-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_shop_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('cancellation_rate', models.FloatField(default=0.0)),
                ('repeat_customer_rate', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('top_service', models.CharField(blank=True, max_length=255, null=True)),
                ('peak_booking_time', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_demographics', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.shop')),
            ],
        ),
    ]
