# Generated by Django 5.2.5 on 2025-10-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_performanceanalytics'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutoFillSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('no_show_window_minutes', models.PositiveIntegerField(default=10, help_text='Minutes after start time to mark as no-show.')),
                ('auto_fill_scope_hours', models.PositiveIntegerField(default=48, help_text='How many hours into the future to look for candidates.')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='api.shop')),
            ],
        ),
        migrations.CreateModel(
            name='AutoFillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='initiated', max_length=30)),
                ('revenue_recovered', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_by_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autofill_success', to='payments.booking')),
                ('original_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autofill_trigger', to='payments.booking')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autofill_logs', to='api.shop')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opted_in_offers', models.BooleanField(default=True, help_text='User agrees to receive short-notice offers.')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='api.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'shop', 'service')},
            },
        ),
    ]
