# Generated by Django 5.2.5 on 2025-10-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aiautofillsettings_autofilllog_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ai_partner_name',
            field=models.CharField(blank=True, default='Amara', max_length=50, null=True),
        ),
    ]
