# Generated by Django 5.2.5 on 2025-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shop_ai_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceanalytics',
            name='no_shows_filled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performanceanalytics',
            name='week_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
