# Generated by Django 5.2.5 on 2025-10-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_performanceanalytics_no_shows_filled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilllog',
            name='offered_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autofill_log', to='api.slot'),
        ),
    ]
