# Generated by Django 5.2.5 on 2025-10-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_autofilllog_offered_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_age_18_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
