# Generated by Django 5.2.5 on 2025-10-29 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_service_requires_age_18_plus_shop_business_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('total_appointments', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rebooking_rate', models.FloatField(default=0.0)),
                ('growth_rate', models.FloatField(default=0.0)),
                ('no_shows_filled', models.PositiveIntegerField(default=0)),
                ('top_service', models.CharField(blank=True, max_length=255)),
                ('top_service_count', models.PositiveIntegerField(default=0)),
                ('open_slots_next_week', models.PositiveIntegerField(default=0)),
                ('forecast_estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ai_motivation', models.TextField(blank=True)),
                ('ai_recommendations', models.JSONField(blank=True, default=dict)),
                ('delivered_channels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='api.shop')),
            ],
            options={
                'ordering': ['-week_end_date', '-created_at'],
            },
        ),
    ]
