# Generated by Django 5.2.5 on 2025-11-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_weeklysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Snapshot of the add-on price at the time of booking', max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='api.slotbooking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_bookings', to='api.service')),
            ],
        ),
    ]
