# Generated by Django 5.2.5 on 2025-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_weeklysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='niche',
            field=models.CharField(choices=[('fitness_trainer', 'Fitness Trainer'), ('tattoo_artist', 'Tattoo Artist'), ('barber', 'Barber'), ('hairstylist', 'Hairstylist'), ('nail_tech', 'Nail Tech'), ('makeup_artist', 'Makeup Artist'), ('esthetician', 'Esthetician'), ('massage_therapist', 'Massage Therapist'), ('other', 'Other')], default='other', help_text='The primary category of the service provider', max_length=50),
        ),
    ]
