# Generated by Django 5.2.5 on 2025-12-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bookingaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='time_zone',
            field=models.CharField(default='America/New_York', help_text="IANA timezone (e.g., 'America/New_York', 'America/Los_Angeles')", max_length=50),
        ),
    ]
