# Generated by Django 5.2.5 on 2025-12-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_shop_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='api.service')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='api.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
