# Generated by Django 5.2.5 on 2025-11-25 14:13

from django.db import migrations, models


def migrate_niche_to_niches(apps, schema_editor):
    """Convert single niche field to niches list"""
    Shop = apps.get_model('api', 'Shop')
    
    for shop in Shop.objects.all():
        # If shop has a niche and niches is empty, migrate it
        if shop.niche and (not shop.niches or len(shop.niches) == 0):
            shop.niches = [shop.niche]
            shop.save(update_fields=['niches'])
    
    print(f"Migrated {Shop.objects.count()} shops from niche to niches")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_consentformtemplate_designrequest_designrequestimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='niches',
            field=models.JSONField(blank=True, default=list, help_text="List of service niches offered by this shop (e.g., ['tattoo_artist', 'barber'])"),
        ),
        migrations.AlterField(
            model_name='shop',
            name='niche',
            field=models.CharField(choices=[('fitness_trainer', 'Fitness Trainer'), ('tattoo_artist', 'Tattoo Artist'), ('barber', 'Barber'), ('hairstylist', 'Hairstylist'), ('nail_tech', 'Nail Tech'), ('makeup_artist', 'Makeup Artist'), ('esthetician', 'Esthetician'), ('massage_therapist', 'Massage Therapist'), ('other', 'Other')], default='other', help_text="DEPRECATED: Use 'niches' field instead. Kept for backward compatibility.", max_length=50),
        ),
        migrations.RunPython(migrate_niche_to_niches, reverse_code=migrations.RunPython.noop),
    ]
