# Generated by Django 5.2.5 on 2026-01-09 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_gallery_and_social_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('interval_minutes', models.PositiveIntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (30, '30 min'), (60, '60 min')], default=15)),
                ('weekly_rules', models.JSONField(default=dict)),
                ('breaks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_deposit_required',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='service',
            name='allow_processing_overlap',
            field=models.BooleanField(default=False, help_text='If True, provider can start new bookings after provider_block_minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='buffer_after_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Buffer time required after this service (in minutes)'),
        ),
        migrations.AddField(
            model_name='service',
            name='buffer_before_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Buffer time required before this service (in minutes)'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider_block_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes provider is actively occupied. Defaults to duration if not set.', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='access_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Optional access hours that constrain all providers'),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_interval_minutes',
            field=models.PositiveIntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (30, '30 min'), (60, '60 min')], default=15, help_text='Default slot interval for time selection grid'),
        ),
        migrations.AddField(
            model_name='shop',
            name='use_rule_based_availability',
            field=models.BooleanField(default=False, help_text='Enable new rule-based availability engine for this shop'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='weeklysummary',
                    name='revenue_checkout',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='Total checkout payments (remaining + tips) this week', max_digits=10),
                ),
                migrations.AddField(
                    model_name='weeklysummary',
                    name='revenue_deposits',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='Total deposits collected this week', max_digits=10),
                ),
                migrations.AddField(
                    model_name='weeklysummary',
                    name='revenue_tips',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='Total tips collected this week', max_digits=10),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE "api_weeklysummary" ADD COLUMN IF NOT EXISTS "revenue_checkout" numeric(10, 2) NOT NULL DEFAULT 0;
                    ALTER TABLE "api_weeklysummary" ADD COLUMN IF NOT EXISTS "revenue_deposits" numeric(10, 2) NOT NULL DEFAULT 0;
                    ALTER TABLE "api_weeklysummary" ADD COLUMN IF NOT EXISTS "revenue_tips" numeric(10, 2) NOT NULL DEFAULT 0;
                    """,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='unverified', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_availability_ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_shops', to='api.availabilityruleset'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('employee', 'Employee'), ('independent', 'Independent')], default='employee', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='providers/')),
                ('allow_any_provider_booking', models.BooleanField(default=True)),
                ('max_concurrent_processing_jobs', models.PositiveIntegerField(default=1, help_text='Maximum number of processing-phase services this provider can handle simultaneously')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='api.availabilityruleset')),
                ('services', models.ManyToManyField(blank=True, related_name='providers', to='api.service')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='api.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('override_rules', models.JSONField(blank=True, default=list)),
                ('override_breaks', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_deposit_required', models.BooleanField(default=False, help_text='Is a deposit required for booking?')),
                ('is_verified', models.BooleanField(default=False)),
                ('last_weekly_wrap_sent_at', models.DateTimeField(blank=True, help_text='When weekly wrap-up notification was last sent (stored in UTC)', null=True)),
                ('last_week_ahead_sent_at', models.DateTimeField(blank=True, help_text='When week-ahead forecast was last sent (stored in UTC)', null=True)),
                ('last_daily_snapshot_sent_at', models.DateTimeField(blank=True, help_text='When daily snapshot was last sent (stored in UTC)', null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='api.provider')),
            ],
            options={
                'unique_together': {('provider', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProviderDayLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_locks', to='api.provider')),
            ],
            options={
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
