# Generated by Django 5.2.5 on 2025-12-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bookingaddon'),
        ('api', '0014_consultation'),
    ]

    operations = [
    ]
