# Generated by Django 5.2.5 on 2026-01-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_availabilityruleset_remove_shop_is_deposit_required_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerdaylock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='providerdaylock',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_locks', to='api.shop'),
        ),

        migrations.AddField(
            model_name='slotbooking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_bookings', to='api.provider'),
        ),
        migrations.AlterField(
            model_name='providerdaylock',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_locks', to='api.provider'),
        ),
        migrations.AddConstraint(
            model_name='providerdaylock',
            constraint=models.UniqueConstraint(fields=('shop', 'provider', 'date'), name='uniq_shop_provider_date_lock'),
        ),
    ]
