# Generated by Django 5.2.5 on 2026-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_providerdaylock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='niche',
            field=models.CharField(blank=True, default='Barber', max_length=50, null=True),
        ),
    ]
