# Generated by Django 5.2.5 on 2025-12-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_gallery_and_social_links'),
        ('api', '0015_merge_0011_bookingaddon_0014_consultation'),
    ]

    operations = [
    ]
