# Generated by Django 5.2.5 on 2025-12-15 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20251212_1802'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('total_points_redeemed', models.PositiveIntegerField(default=0)),
                ('last_earned_at', models.DateTimeField(blank=True, null=True)),
                ('last_redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Loyalty points',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=1.0, help_text='Points earned per dollar spent', max_digits=5)),
                ('points_for_redemption', models.PositiveIntegerField(default=100, help_text='Points needed to redeem a reward')),
                ('reward_type', models.CharField(choices=[('discount_percent', 'Discount (%)'), ('discount_fixed', 'Discount ($)'), ('free_service', 'Free Service')], default='discount_percent', max_length=20)),
                ('reward_value', models.DecimalField(decimal_places=2, default=10.0, help_text='Discount percentage or fixed amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalkInEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('position', models.PositiveIntegerField(default=0, help_text='Queue position')),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_service', 'In Service'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Walk-in entries',
                'ordering': ['position', 'joined_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='idverificationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='consultation',
            new_name='api_consult_shop_id_284ad9_idx',
            old_name='api_consult_shop_id_date_status_idx',
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_customers', to='api.shop'),
        ),
        migrations.AddField(
            model_name='loyaltypoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='api.shop'),
        ),
        migrations.AddField(
            model_name='walkinentry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_ins', to='api.service'),
        ),
        migrations.AddField(
            model_name='walkinentry',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_ins', to='api.shop'),
        ),
        migrations.AddField(
            model_name='walkinentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='loyaltypoints',
            unique_together={('shop', 'user')},
        ),
        migrations.AddIndex(
            model_name='walkinentry',
            index=models.Index(fields=['shop', 'status', 'joined_at'], name='api_walkine_shop_id_e74cfe_idx'),
        ),
    ]
