# Generated by Django 5.2.5 on 2026-01-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_shop_niche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityexception',
            name='is_deposit_required',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='last_daily_snapshot_sent_at',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='last_week_ahead_sent_at',
        ),
        migrations.RemoveField(
            model_name='availabilityexception',
            name='last_weekly_wrap_sent_at',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='shop',
                    name='last_daily_snapshot_sent_at',
                    field=models.DateTimeField(blank=True, help_text='When daily snapshot was last sent (stored in UTC)', null=True),
                ),
                migrations.AddField(
                    model_name='shop',
                    name='last_week_ahead_sent_at',
                    field=models.DateTimeField(blank=True, help_text='When week-ahead forecast was last sent (stored in UTC)', null=True),
                ),
                migrations.AddField(
                    model_name='shop',
                    name='last_weekly_wrap_sent_at',
                    field=models.DateTimeField(blank=True, help_text='When weekly wrap-up notification was last sent (stored in UTC)', null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE "api_shop" ADD COLUMN IF NOT EXISTS "last_daily_snapshot_sent_at" timestamp with time zone NULL;
                    ALTER TABLE "api_shop" ADD COLUMN IF NOT EXISTS "last_week_ahead_sent_at" timestamp with time zone NULL;
                    ALTER TABLE "api_shop" ADD COLUMN IF NOT EXISTS "last_weekly_wrap_sent_at" timestamp with time zone NULL;
                    """,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=12),
        ),
    ]
