# Generated by Django 5.2.5 on 2026-01-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_availabilityexception_is_deposit_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or description of the provider', null=True),
        ),
    ]
