# Generated by Django 5.2.5 on 2025-12-15 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_barber_walkin_loyalty'),
        ('payments', '0007_checkout_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_fill_in',
            field=models.BooleanField(default=False, help_text='True for fill-in, False for new set'),
        ),
        migrations.AddField(
            model_name='service',
            name='nail_shape',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('coffin', 'Coffin'), ('almond', 'Almond'), ('stiletto', 'Stiletto'), ('square', 'Square'), ('round', 'Round'), ('oval', 'Oval'), ('squoval', 'Squoval')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='nail_style_type',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('acrylic', 'Acrylic'), ('gel', 'Gel'), ('dip', 'Dip Powder'), ('natural', 'Natural/Manicure'), ('pedicure', 'Pedicure'), ('nail_art', 'Nail Art')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='StyleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text="Client's style description")),
                ('nail_style_type', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('acrylic', 'Acrylic'), ('gel', 'Gel'), ('dip', 'Dip Powder'), ('natural', 'Natural/Manicure'), ('pedicure', 'Pedicure'), ('nail_art', 'Nail Art')], max_length=20)),
                ('nail_shape', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('coffin', 'Coffin'), ('almond', 'Almond'), ('stiletto', 'Stiletto'), ('square', 'Square'), ('round', 'Round'), ('oval', 'Oval'), ('squoval', 'Squoval')], max_length=20)),
                ('color_preference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_requests', to='payments.booking')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_requests', to='api.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='style_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('style_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.stylerequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='stylerequest',
            index=models.Index(fields=['shop', 'status'], name='api_stylere_shop_id_3de774_idx'),
        ),
    ]
