# Generated by Django 5.2.5 on 2026-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_provider_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='verified', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='use_rule_based_availability',
            field=models.BooleanField(default=True, help_text='Enable new rule-based availability engine for this shop'),
        ),
    ]
