# Generated by Django 5.2.5 on 2025-12-17 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_nailtech_stylerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Link to client for Face Charts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='look_type',
            field=models.CharField(blank=True, help_text='For MUA face charts: natural, glam, bridal, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='is_mobile_service',
            field=models.BooleanField(default=False, help_text='Can travel to client location'),
        ),
        migrations.AddField(
            model_name='service',
            name='look_type',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('natural', 'Natural'), ('glam', 'Glam'), ('bridal', 'Bridal'), ('editorial', 'Editorial'), ('sfx', 'Special Effects')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('foundation', 'Foundation'), ('concealer', 'Concealer'), ('powder', 'Powder'), ('blush', 'Blush'), ('bronzer', 'Bronzer'), ('highlighter', 'Highlighter'), ('eyeshadow', 'Eyeshadow'), ('eyeliner', 'Eyeliner'), ('mascara', 'Mascara'), ('brow', 'Brow Products'), ('lipstick', 'Lipstick'), ('lip_gloss', 'Lip Gloss'), ('primer', 'Primer'), ('setting_spray', 'Setting Spray'), ('brush', 'Brush'), ('sponge', 'Sponge/Applicator'), ('skincare', 'Skincare'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_packed', models.BooleanField(default=False, help_text='Checked off in kit')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_kit', to='api.shop')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientBeautyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(blank=True, choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('olive', 'Olive'), ('tan', 'Tan'), ('deep', 'Deep')], max_length=20)),
                ('skin_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('sensitive', 'Sensitive')], max_length=20)),
                ('undertone', models.CharField(blank=True, choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], max_length=20)),
                ('allergies', models.TextField(blank=True, help_text='Product allergies or sensitivities')),
                ('preferences', models.TextField(blank=True, help_text='General beauty preferences and notes')),
                ('foundation_shade', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_profiles', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_profiles', to='api.shop')),
            ],
            options={
                'verbose_name_plural': 'Client beauty profiles',
                'unique_together': {('shop', 'client')},
            },
        ),
    ]
