# Generated by Django 5.2.5 on 2025-12-18 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_mua_dashboard'),
        ('payments', '0008_hairstylist_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hair_service_type',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('cut', 'Cut'), ('color', 'Color'), ('style', 'Style'), ('treatment', 'Treatment'), ('braids', 'Braids'), ('locs', 'Locs'), ('extensions', 'Extensions'), ('wash', 'Wash & Style')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='includes_consultation',
            field=models.BooleanField(default=False, help_text='Service includes consultation'),
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('shampoo', 'Shampoo'), ('conditioner', 'Conditioner'), ('treatment', 'Treatment'), ('oil', 'Oil'), ('styling', 'Styling Product'), ('protectant', 'Heat Protectant'), ('leave_in', 'Leave-In'), ('mask', 'Hair Mask'), ('color', 'Color Product'), ('tool', 'Tool/Accessory'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Usage instructions or notes')),
                ('purchase_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_recommendations', to='payments.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recommendations', to='api.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientHairProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_type', models.CharField(blank=True, choices=[('1a', '1A - Fine Straight'), ('1b', '1B - Medium Straight'), ('1c', '1C - Coarse Straight'), ('2a', '2A - Fine Wavy'), ('2b', '2B - Medium Wavy'), ('2c', '2C - Coarse Wavy'), ('3a', '3A - Loose Curls'), ('3b', '3B - Springy Curls'), ('3c', '3C - Tight Curls'), ('4a', '4A - Soft Coils'), ('4b', '4B - Z-Pattern Coils'), ('4c', '4C - Tight Coils')], max_length=10)),
                ('hair_texture', models.CharField(blank=True, choices=[('fine', 'Fine'), ('medium', 'Medium'), ('coarse', 'Coarse')], max_length=20)),
                ('hair_porosity', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], max_length=20)),
                ('natural_color', models.CharField(blank=True, max_length=50)),
                ('current_color', models.CharField(blank=True, max_length=50)),
                ('color_history', models.TextField(blank=True, help_text='Previous color treatments')),
                ('chemical_history', models.TextField(blank=True, help_text='Relaxers, perms, keratin, etc.')),
                ('scalp_condition', models.CharField(blank=True, help_text='Dry, oily, sensitive, etc.', max_length=100)),
                ('allergies', models.TextField(blank=True, help_text='Product allergies or sensitivities')),
                ('preferences', models.TextField(blank=True, help_text='Style preferences and notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_profiles', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_profiles', to='api.shop')),
            ],
            options={
                'verbose_name_plural': 'Client hair profiles',
                'unique_together': {('shop', 'client')},
            },
        ),
    ]
