# Generated by Django 5.2.5 on 2026-01-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_shop_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationfile',
            name='file',
            field=models.FileField(upload_to='verification_files/'),
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('break', 'Break'), ('pto', 'PTO'), ('other', 'Other')], default='break', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='If null, blocks the entire shop (all providers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='api.provider')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='api.shop')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['shop', 'start_at', 'end_at'], name='api_blocked_shop_id_941a99_idx'), models.Index(fields=['provider', 'start_at', 'end_at'], name='api_blocked_provide_f1891e_idx')],
            },
        ),
    ]
