# Generated by Django 5.2.5 on 2025-12-18 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_hairstylist_dashboard'),
        ('payments', '0008_hairstylist_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='niche',
            field=models.CharField(choices=[('general', 'General'), ('hair', 'Hair'), ('esthetician', 'Esthetician'), ('massage', 'Massage')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='esthetician_service_type',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('facial', 'Facial'), ('massage', 'Massage'), ('body', 'Body Treatment'), ('wax', 'Waxing'), ('lash', 'Lash/Brow'), ('peel', 'Chemical Peel'), ('microderm', 'Microdermabrasion'), ('wrap', 'Body Wrap'), ('scrub', 'Body Scrub')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_health_disclosure',
            field=models.BooleanField(default=False, help_text='Requires health disclosure form'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='category',
            field=models.CharField(choices=[('shampoo', 'Shampoo'), ('conditioner', 'Conditioner'), ('treatment', 'Treatment'), ('oil', 'Oil'), ('styling', 'Styling Product'), ('protectant', 'Heat Protectant'), ('leave_in', 'Leave-In'), ('mask', 'Hair Mask'), ('color', 'Color Product'), ('cleanser', 'Cleanser'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('exfoliant', 'Exfoliant'), ('toner', 'Toner'), ('eye_cream', 'Eye Cream'), ('tool', 'Tool/Accessory'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='HealthDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_medical_conditions', models.BooleanField(default=False)),
                ('conditions_detail', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('pregnant_or_nursing', models.BooleanField(default=False)),
                ('recent_surgeries', models.TextField(blank=True)),
                ('pressure_preference', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('firm', 'Firm'), ('deep', 'Deep Tissue')], max_length=20)),
                ('areas_to_avoid', models.TextField(blank=True)),
                ('areas_to_focus', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_disclosures', to='payments.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_disclosures', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disclosures', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_disclosures', to='api.shop')),
            ],
            options={
                'verbose_name_plural': 'Health disclosures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetailProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('cleanser', 'Cleanser'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('mask', 'Mask'), ('exfoliant', 'Exfoliant'), ('toner', 'Toner'), ('eye_cream', 'Eye Cream'), ('oil', 'Oil'), ('body_care', 'Body Care'), ('tool', 'Tool/Accessory'), ('other', 'Other')], default='other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('purchase_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_products', to='api.shop')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('facial', 'Facial'), ('massage', 'Massage'), ('body', 'Body Treatment'), ('wax', 'Waxing'), ('lash', 'Lash/Brow'), ('peel', 'Chemical Peel'), ('microderm', 'Microdermabrasion'), ('wrap', 'Body Wrap'), ('scrub', 'Body Scrub'), ('other', 'Other')], max_length=20)),
                ('products_used', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('next_appointment_notes', models.TextField(blank=True)),
                ('before_photo_url', models.URLField(blank=True)),
                ('after_photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_note', to='payments.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_notes', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_notes', to='api.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientSkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive')], max_length=20)),
                ('primary_concerns', models.JSONField(default=list, help_text="['acne', 'aging', 'pigmentation']")),
                ('allergies', models.TextField(blank=True)),
                ('sensitivities', models.TextField(blank=True)),
                ('current_products', models.TextField(blank=True, help_text='Products client currently uses')),
                ('morning_routine', models.JSONField(default=list, help_text='[{step, product, notes}]')),
                ('evening_routine', models.JSONField(default=list)),
                ('weekly_treatments', models.JSONField(default=list)),
                ('regimen_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profiles', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profiles', to='api.shop')),
            ],
            options={
                'verbose_name_plural': 'Client skin profiles',
                'unique_together': {('shop', 'client')},
            },
        ),
    ]
