# Generated by Django 5.2.5 on 2026-02-03 00:00

from django.db import migrations


def verify_all_shops(apps, schema_editor):
    Shop = apps.get_model("api", "Shop")
    Shop.objects.exclude(status="verified").update(status="verified")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_verificationfile_file_blockedtime"),
    ]

    operations = [
        migrations.RunPython(verify_all_shops, migrations.RunPython.noop),
    ]
