# Generated by Django 5.2.5 on 2025-09-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_chatthread_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, help_text='Total revenue amount', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this revenue record was created')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='api.shop')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenues',
                'ordering': ['-timestamp'],
            },
        ),
    ]
