# Generated by Django 5.2.5 on 2025-12-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_esthetician_dashboard'),
        ('payments', '0008_hairstylist_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_used', models.CharField(choices=[('swedish', 'Swedish'), ('deep_tissue', 'Deep Tissue'), ('hot_stone', 'Hot Stone'), ('sports', 'Sports Massage'), ('prenatal', 'Prenatal'), ('reflexology', 'Reflexology'), ('trigger_point', 'Trigger Point'), ('lymphatic', 'Lymphatic Drainage'), ('thai', 'Thai Massage'), ('other', 'Other')], max_length=20)),
                ('pressure_applied', models.CharField(blank=True, max_length=20)),
                ('areas_worked', models.TextField(blank=True)),
                ('tension_observations', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True, help_text='Stretches, home care, etc.')),
                ('next_session_notes', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_note', to='payments.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='api.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientMassageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_preference', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('firm', 'Firm'), ('deep', 'Deep Tissue')], max_length=20)),
                ('areas_to_focus', models.TextField(blank=True, help_text='Shoulders, neck, lower back, etc.')),
                ('areas_to_avoid', models.TextField(blank=True, help_text='Injured areas, sensitive spots')),
                ('has_injuries', models.BooleanField(default=False)),
                ('injury_details', models.TextField(blank=True)),
                ('has_chronic_conditions', models.BooleanField(default=False)),
                ('chronic_conditions', models.TextField(blank=True, help_text='Arthritis, fibromyalgia, etc.')),
                ('preferred_techniques', models.JSONField(default=list, help_text="['swedish', 'deep_tissue', 'hot_stone']")),
                ('temperature_preference', models.CharField(blank=True, help_text='warm, cool, no preference', max_length=20)),
                ('music_preference', models.CharField(blank=True, max_length=50)),
                ('aromatherapy_preference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_profiles', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_profiles', to='api.shop')),
            ],
            options={
                'verbose_name_plural': 'Client massage profiles',
                'unique_together': {('shop', 'client')},
            },
        ),
    ]
