# Generated by Django 5.2.5 on 2025-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='timestamp',
            field=models.DateTimeField(help_text='When this revenue record was created'),
        ),
    ]
