# Generated by Django 5.2.5 on 2025-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_revenue_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When this revenue record was created'),
        ),
    ]
