# Generated by Django 5.2.5 on 2026-01-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_massage_therapist_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='service_niche',
            field=models.CharField(blank=True, help_text='Service niche: tattoo_artist, nail_tech, hairstylist, etc.', max_length=50, null=True),
        ),
    ]
