# Generated by Django 5.2.5 on 2026-01-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_massage_therapist_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='service_niche',
            field=models.CharField(blank=True, help_text='Service niche: tattoo_artist, nail_tech, hairstylist, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_daily_snapshot_sent_at',
            field=models.DateTimeField(blank=True, help_text='When daily snapshot was last sent (stored in UTC)', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_week_ahead_sent_at',
            field=models.DateTimeField(blank=True, help_text='When week-ahead forecast was last sent (stored in UTC)', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_weekly_wrap_sent_at',
            field=models.DateTimeField(blank=True, help_text='When weekly wrap-up notification was last sent (stored in UTC)', null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='revenue_checkout',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total checkout payments (remaining + tips) this week', max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='revenue_deposits',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total deposits collected this week', max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='revenue_tips',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tips collected this week', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='unverified', max_length=10),
        ),
    ]
