# Generated by Django 5.2.5 on 2025-09-09 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_revenue_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slotbooking',
            name='uniq_user_slot',
        ),
        migrations.AddConstraint(
            model_name='slotbooking',
            constraint=models.UniqueConstraint(fields=('user', 'slot', 'status'), name='uniq_user_slot_status'),
        ),
    ]
