# Generated by Django 5.2.5 on 2026-01-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_verificationfile_file_blockedtime'),
        ('api', '0024_walk_in_queue_support'),
    ]

    operations = [
    ]
