# Generated by Django 5.2.5 on 2025-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_slotbooking_uniq_user_slot_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fcm_token',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
