# Generated by Django 5.2.5 on 2025-09-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_device_fcm_token'),
        ('payments', '0003_booking_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='payments.booking'),
        ),
    ]
