# Generated by Django 5.2.5 on 2025-09-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_revenue_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='timestamp',
            field=models.DateField(help_text='Revenue record date'),
        ),
    ]
