# Generated by Django 5.2.5 on 2025-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_revenue_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='timestamp',
            field=models.DateField(auto_now_add=True, help_text='Revenue record date'),
        ),
    ]
