# Generated by Django 5.2.5 on 2025-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_revenue_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=10),
        ),
    ]
