# Generated by Django 5.2.5 on 2025-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_slotbooking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
