# Generated by Django 5.2.5 on 2025-09-22 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_slotbooking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 12, 0)),
            preserve_default=False,
        ),
    ]
