# Generated by Django 5.2.5 on 2025-09-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_slotbooking_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('refund', 'Refund')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount value. Flat or percentage depending on in_percentage', max_digits=10, null=True)),
                ('in_percentage', models.BooleanField(default=False, help_text='If True, discount is percentage-based')),
                ('validity_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_usage_per_user', models.PositiveIntegerField(blank=True, help_text='Max times a user can use this coupon', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_coupons', to='api.service')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_coupons', to='api.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
