# Generated by Django 5.2.5 on 2025-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_service_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='service',
        ),
        migrations.AddField(
            model_name='coupon',
            name='services',
            field=models.ManyToManyField(related_name='service_coupons', to='api.service'),
        ),
    ]
