# Generated by Django 5.2.5 on 2025-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_coupon_service_coupon_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='fcm_token',
            field=models.CharField(max_length=255),
        ),
    ]
