# Generated by Django 5.2.5 on 2025-09-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_device_device_token_alter_device_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
