# Generated by Django 5.2.5 on 2025-09-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_shop_break_end_time_shop_break_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cancellation_fee_percentage',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='free_cancellation_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='shop',
            name='no_refund_hours',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
