# Generated by Django 5.2.5 on 2025-09-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_shop_cancellation_fee_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDisabledTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(db_index=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_times', to='api.service')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('service', 'start_time')},
            },
        ),
    ]
