# Generated by Django 5.2.5 on 2025-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_servicedisabledtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The fixed amount for the deposit.', max_digits=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_deposit_required',
            field=models.BooleanField(default=False, help_text='Is a deposit required for booking?'),
        ),
    ]
