# Generated by Django 5.2.5 on 2025-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_shop_deposit_amount_shop_is_deposit_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
