# Generated by Django 5.2.5 on 2025-10-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_shop_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='stripe_customer_id',
        ),
    ]
