# Generated by Django 5.2.5 on 2025-10-01 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0039_servicedisabledtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Foundation', 'Foundation'), ('Momentum', 'Momentum'), ('Icon', 'Icon')], max_length=50, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Percentage rate, e.g., 10.00 for 10%', max_digits=5)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for this plan', max_length=100, null=True)),
                ('marketplace_profile', models.BooleanField(default=True)),
                ('instant_booking_payments', models.BooleanField(default=True)),
                ('automated_reminders', models.BooleanField(default=True)),
                ('smart_rebooking_prompts', models.BooleanField(default=True)),
                ('deposit_customization', models.CharField(choices=[('default', 'Default only'), ('basic', 'Basic'), ('advanced', 'Advanced')], default='default', max_length=20)),
                ('priority_marketplace_ranking', models.BooleanField(default=False)),
                ('advanced_calendar_tools', models.BooleanField(default=False)),
                ('auto_followups', models.BooleanField(default=False)),
                ('ai_assistant', models.CharField(choices=[('addon', 'Add-on'), ('included', 'Included')], default='addon', max_length=20)),
                ('performance_analytics', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('advanced', 'Advanced')], default='none', max_length=20)),
                ('ghost_client_reengagement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.shop')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
