# Generated by Django 5.2.5 on 2025-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='performance_analytics',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('moderate', 'Moderate'), ('advanced', 'Advanced')], default='none', max_length=20),
        ),
    ]
