# Generated by Django 5.2.5 on 2025-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionplan_performance_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Momentum', 'Momentum'), ('Icon', 'Icon')], db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='priority_marketplace_ranking',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
