# Generated by Django 5.2.5 on 2025-10-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionplan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsubscription',
            name='has_ai_addon',
            field=models.BooleanField(default=False),
        ),
    ]
