# Generated by Django 5.2.5 on 2025-10-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_shopsubscription_has_ai_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsubscription',
            name='legacy_ai_promo_used',
            field=models.BooleanField(default=False),
        ),
    ]
