# Generated by Django 5.2.5 on 2025-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_shopsubscription_legacy_ai_promo_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsubscription',
            name='ai_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='ai_subscription_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
