# Generated by Django 5.2.5 on 2025-11-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_shopsubscription_ai_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsubscription',
            name='paypal_ai_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
