# Generated by Django 5.2.5 on 2025-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_shopsubscription_paypal_ai_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, help_text='PayPal Billing Plan ID for this subscription tier', max_length=255, null=True),
        ),
    ]
