# Generated by Django 5.2.5 on 2025-11-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscriptionplan_paypal_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsubscription',
            name='ai_subscription_id',
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='ai_paypal_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='ai_stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopsubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, help_text='PayPal subscription ID returned on approval', max_length=255, null=True),
        ),
    ]
