from django.urls import path
from .views import (
    ShopListCreateView,
    ShopRetrieveUpdateDestroyView,
    ServiceListCreateView,
    ServiceRetrieveUpdateDestroyView,
    UserRatingReviewView,
    ServiceCategoryListView,
    # SlotListView,
    SlotBookingView,
    CancelSlotBookingView,
    AllShopsListView,
    ShopDetailView,
    AllServicesListView,
    ServiceDetailView,
    FavoriteShopView,
    PromotionListView,
    ServiceWishlistView,
    GlobalSearchView,
    ReplyCreateView,
    ShopRatingReviewsView, 
    UserMessageView, 
    OwnerMessageView, 
    ThreadListView, 
    RegisterDeviceView,
    NotificationsView,
    NotificationDetailView,
    WeeklyShopRevenueView,
    GrowthSuggestionView,
    CouponListCreateAPIView,
    CouponRetrieveUpdateDestroyAPIView,
    UserCouponRetrieveAPIView,
    BestServicePerShopView,
    ThreadDetailsView,
)
from payments.views import ShopSlotsView

urlpatterns = [
    path('shop/', ShopListCreateView.as_view(), name='shop-list-create'),
    path('shop/<int:pk>/', ShopRetrieveUpdateDestroyView.as_view(), name='shop-detail'),
    path('services/', ServiceListCreateView.as_view(), name='service-list-create'),
    path('services/<int:pk>/', ServiceRetrieveUpdateDestroyView.as_view(), name='service-detail'),
    path('reviews/', UserRatingReviewView.as_view(), name='user-reviews'),
    path('categories/', ServiceCategoryListView.as_view(), name='category-list'),
    path('shops/<int:shop_id>/slots/', ShopSlotsView.as_view(), name='slot-list'),
    path('slot-booking/', SlotBookingView.as_view(), name='slot-booking-create'),
    path('slot-booking/<int:booking_id>/cancel/', CancelSlotBookingView.as_view(), name='slot-booking-cancel'),
    path('users/shops/', AllShopsListView.as_view(), name='all-shops-list-user'),
    path('users/shops/details/<int:shop_id>/', ShopDetailView.as_view(), name='shop-detail-user'),
    path("users/services/", AllServicesListView.as_view(), name="all-services"),
    path("users/services/<int:service_id>/", ServiceDetailView.as_view(), name="service-detail"),
    path('users/favorite-shop/', FavoriteShopView.as_view(), name='favorite-shop'),
    path('promotions/', PromotionListView.as_view(), name='promotion-list'),
    path('users/service-wishlist/', ServiceWishlistView.as_view(), name='service-wishlist'),
    path('global-search/', GlobalSearchView.as_view(), name='global-search'),
    path('create-reply/<int:rating_review_id>/', ReplyCreateView.as_view(), name='reply-create'),
    path('shops/rating-reviews/<int:shop_id>/', ShopRatingReviewsView.as_view(), name='shop-rating-reviews'),
    path("threads/", ThreadListView.as_view(), name="thread-list"),
    path("threads/<int:thread_id>/", ThreadDetailsView.as_view(), name="thread-detail"),
    path("threads/<int:shop_id>/send/", UserMessageView.as_view(), name="user-send-message"),
    path("threads/<int:thread_id>/reply/", OwnerMessageView.as_view(), name="owner-reply-message"),
    path('register-device/', RegisterDeviceView.as_view(), name='register-device'),
    path("notifications/", NotificationsView.as_view(), name="user-notifications"),
    path("notifications/<int:pk>/", NotificationDetailView.as_view(), name="notification-detail"),
    path('shop/<int:shop_id>/revenues/', WeeklyShopRevenueView.as_view(), name='weekly-shop-revenues'),
    path("growth-suggestions/", GrowthSuggestionView.as_view(), name="growth-suggestions"),
    path('coupons/', CouponListCreateAPIView.as_view(), name='coupon-list-create'),
    path('coupons/<int:coupon_id>/', CouponRetrieveUpdateDestroyAPIView.as_view(), name='coupon-detail'),
    path('users/coupons/', UserCouponRetrieveAPIView.as_view(), name='user-get-coupon'),
    path('best-service/<int:shop_id>/', BestServicePerShopView.as_view(), name="best-service-per-shop"),
]
